#
# Copyright (c) 2022 Airbyte, Inc., all rights reserved.
#


import json
from datetime import datetime
import os
from os.path import exists
from typing import Dict, Generator
from git import Repo, Diff
from typing import cast



from airbyte_cdk.logger import AirbyteLogger
from airbyte_cdk.models import (
    AirbyteCatalog,
    AirbyteConnectionStatus,
    AirbyteMessage,
    AirbyteRecordMessage,
    AirbyteStateMessage,
    AirbyteStream,
    ConfiguredAirbyteCatalog,
    AirbyteGlobalState,
    Status,
    SyncMode,
    Type,
)
from airbyte_cdk.sources import Source

from pathlib import Path

def rmdir(directory):
    directory = Path(directory)
    for item in directory.iterdir():
        if item.is_dir():
            rmdir(item)
        else:
            item.unlink()
    directory.rmdir()

def safeRead(blob):
    try:
        return cast(str, blob.read().decode('UTF-8'))
    except UnicodeDecodeError:
        return ""



class SourceGitFile(Source):
    def check(self, logger: AirbyteLogger, config: json) -> AirbyteConnectionStatus:
        """
        Tests if the input configuration can be used to successfully connect to the integration
            e.g: if a provided Stripe API token can be used to connect to the Stripe API.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.yaml file

        :return: AirbyteConnectionStatus indicating a Success or Failure
        """
        try:
            # Not Implemented

            return AirbyteConnectionStatus(status=Status.SUCCEEDED)
        except Exception as e:
            return AirbyteConnectionStatus(status=Status.FAILED, message=f"An exception occurred: {str(e)}")

    def discover(self, logger: AirbyteLogger, config: json) -> AirbyteCatalog:
        """
        Returns an AirbyteCatalog representing the available streams and fields in this integration.
        For example, given valid credentials to a Postgres database,
        returns an Airbyte catalog where each postgres table is a stream, and each table column is a field.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.yaml file

        :return: AirbyteCatalog is an object describing a list of all available streams in this source.
            A stream is an AirbyteStream object that includes:
            - its stream name (or table name in the case of Postgres)
            - json_schema providing the specifications of expected schema for this stream (a list of columns described
            by their names and types)
        """
        streams = []

        stream_name = "FileRevisions"  # Example
        json_schema = {  # Example
            "$schema": "http://json-schema.org/draft-07/schema#",
            "type": "object",
            "properties": {
                "hash": {"type": "string"},
                "authorName": {"type": "string"},
                "authorEmail": {"type": "string"},
                "date": {"type": "string", "format": "date-time"},
                "message": {"type": "string"},
                "branch": {"type": "string"},
                "repository": {"type": "string"},
                "size": {"type": "number"},
                "loc": {"type": "number"},
                "fileName": {"type": "string"},
                "operation": {"type": "string"},
                "newContent": {"type": "string"},
                "oldContent": {"type": "string"},
                "oldSize": {"type": "number"},
                "oldLoc": {"type": "number"},
                "oldFileName": {"type": "string"}
            },
        }

        # Not Implemented

        streams.append(AirbyteStream(name=stream_name, json_schema=json_schema, supported_sync_modes=[SyncMode.full_refresh, SyncMode.incremental], source_defined_cursor=True, default_cursor_field=["date"], source_defined_primary_key=[["hash", "fileName", "operation"]] ))
        return AirbyteCatalog(streams=streams)

    def read(
        self, logger: AirbyteLogger, config: json, catalog: ConfiguredAirbyteCatalog, state: Dict[str, any]
    ) -> Generator[AirbyteMessage, None, None]:
        """
        Returns a generator of the AirbyteMessages generated by reading the source with the given configuration,
        catalog, and state.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
            the properties of the spec.yaml file
        :param catalog: The input catalog is a ConfiguredAirbyteCatalog which is almost the same as AirbyteCatalog
            returned by discover(), but
        in addition, it's been configured in the UI! For each particular stream and field, there may have been provided
        with extra modifications such as: filtering streams and/or columns out, renaming some entities, etc
        :param state: When a Airbyte reads data from a source, it might need to keep a checkpoint cursor to resume
            replication in the future from that saved checkpoint.
            This is the object that is provided with state from previous runs and avoid replicating the entire set of
            data everytime.

        :return: A generator that produces a stream of AirbyteRecordMessage contained in AirbyteMessage object.
        """
        stream_name = "FileRevisions"  # Example

        options = ["--depth " + config["depth"]]

        if exists("./tmp_checkout"):
            rmdir(Path("./tmp_checkout"))
        rep = Repo.clone_from(config["repoUrl"], "./tmp_checkout", None, None, options)

        currentDepth = 0

        commitCursor = rep.commit(config["branch"])
        while commitCursor != None:
            prevCommit = None
            currentDepth = currentDepth + 1
            if len(commitCursor.parents) > 0 and currentDepth < int(config["depth"]):
                prevCommit = commitCursor.parents[0]
                currentDiff = prevCommit.diff(commitCursor)
            else:
                # 4b825dc642cb6eb9a060e54bf8d69288fbee4904 is the magical empty commit which is always availble
                currentDiff = rep.tree("4b825dc642cb6eb9a060e54bf8d69288fbee4904").diff(commitCursor)
            if catalog.streams[0].sync_mode == SyncMode.incremental and commitCursor.hexsha == state["lastHash"]:
                break
            for diffAdded in currentDiff.iter_change_type("A"):
                d = cast(Diff, diffAdded)
                blob = safeRead(d.b_blob.data_stream)
                yield AirbyteMessage(
                    type=Type.RECORD,
                    record=AirbyteRecordMessage(stream=stream_name, data={
                        "hash": commitCursor.hexsha,
                        "authorName": commitCursor.author.name,
                        "authorEmail": commitCursor.author.email,
                        "date": commitCursor.committed_datetime.isoformat(),
                        "message": commitCursor.message,
                        "branch": config["branch"],
                        "repository": config["repoUrl"],
                        "size": d.b_blob.size,
                        "loc": len(blob.splitlines()),
                        "fileName": d.b_path,
                        "operation": "add",
                        "newContent": blob,
                        "oldContent": "",
                        "oldSize": 0,
                        "oldLoc": 0,
                        "oldFileName": "",
                    }, emitted_at=int(datetime.now().timestamp()) * 1000),
                )
            for diffDeleted in currentDiff.iter_change_type("D"):
                d = cast(Diff, diffDeleted)
                blob = safeRead(d.a_blob.data_stream)
                yield AirbyteMessage(
                    type=Type.RECORD,
                    record=AirbyteRecordMessage(stream=stream_name, data={
                        "hash": commitCursor.hexsha,
                        "authorName": commitCursor.author.name,
                        "authorEmail": commitCursor.author.email,
                        "date": commitCursor.committed_datetime.isoformat(),
                        "message": commitCursor.message,
                        "branch": config["branch"],
                        "repository": config["repoUrl"],
                        "size": 0,
                        "loc": 0,
                        "fileName": d.a_path,
                        "operation": "remove",
                        "oldContent": blob,
                        "newContent": "",
                        "oldSize": d.a_blob.size,
                        "oldLoc": len(blob.splitlines()),
                        "oldFileName": d.a_path,
                    }, emitted_at=int(datetime.now().timestamp()) * 1000),
                )
            for diffModified in currentDiff.iter_change_type("M"):
                d = cast(Diff, diffModified)
                bBlob = safeRead(d.b_blob.data_stream)
                aBlob = safeRead(d.a_blob.data_stream)
                yield AirbyteMessage(
                    type=Type.RECORD,
                    record=AirbyteRecordMessage(stream=stream_name, data={
                        "hash": commitCursor.hexsha,
                        "authorName": commitCursor.author.name,
                        "authorEmail": commitCursor.author.email,
                        "date": commitCursor.committed_datetime.isoformat(),
                        "message": commitCursor.message,
                        "branch": config["branch"],
                        "repository": config["repoUrl"],
                        "size": d.b_blob.size,
                        "loc": len(bBlob.splitlines()),
                        "fileName": d.b_path,
                        "operation": "add",
                        "newContent": bBlob,
                        "oldContent": aBlob,
                        "oldSize": d.a_blob.size,
                        "oldLoc": len(aBlob.splitlines()),
                        "oldFileName": d.a_path,
                    }, emitted_at=int(datetime.now().timestamp()) * 1000),
                )
                yield AirbyteMessage(
                    type=Type.RECORD,
                    record=AirbyteRecordMessage(stream=stream_name, data={
                        "hash": commitCursor.hexsha,
                        "authorName": commitCursor.author.name,
                        "authorEmail": commitCursor.author.email,
                        "date": commitCursor.committed_datetime.isoformat(),
                        "message": commitCursor.message,
                        "branch": config["branch"],
                        "repository": config["repoUrl"],
                        "size": 0,
                        "loc": 0,
                        "fileName": d.a_path,
                        "operation": "remove",
                        "oldContent": aBlob,
                        "newContent": "",
                        "oldSize": d.a_blob.size,
                        "oldLoc": len(aBlob.splitlines()),
                        "oldFileName": d.a_path,
                    }, emitted_at=int(datetime.now().timestamp()) * 1000),
                )
            for diffRenamed in currentDiff.iter_change_type("R"):
                d = cast(Diff, diffRenamed)
                bBlob = safeRead(d.b_blob.data_stream)
                aBlob = safeRead(d.a_blob.data_stream)
                yield AirbyteMessage(
                    type=Type.RECORD,
                    record=AirbyteRecordMessage(stream=stream_name, data={
                        "hash": commitCursor.hexsha,
                        "authorName": commitCursor.author.name,
                        "authorEmail": commitCursor.author.email,
                        "date": commitCursor.committed_datetime.isoformat(),
                        "message": commitCursor.message,
                        "branch": config["branch"],
                        "repository": config["repoUrl"],
                        "size": d.b_blob.size,
                        "loc": len(bBlob.splitlines()),
                        "fileName": d.b_path,
                        "operation": "add",
                        "newContent": bBlob,
                        "oldContent": aBlob,
                        "oldSize": d.a_blob.size,
                        "oldLoc": len(aBlob.splitlines()),
                        "oldFileName": d.a_path,
                    }, emitted_at=int(datetime.now().timestamp()) * 1000),
                )
                yield AirbyteMessage(
                    type=Type.RECORD,
                    record=AirbyteRecordMessage(stream=stream_name, data={
                        "hash": commitCursor.hexsha,
                        "authorName": commitCursor.author.name,
                        "authorEmail": commitCursor.author.email,
                        "date": commitCursor.committed_datetime.isoformat(),
                        "message": commitCursor.message,
                        "branch": config["branch"],
                        "repository": config["repoUrl"],
                        "size": 0,
                        "loc": 0,
                        "fileName": d.a_path,
                        "operation": "remove",
                        "oldContent": aBlob,
                        "newContent": "",
                        "oldSize": d.a_blob.size,
                        "oldLoc": len(aBlob.splitlines()),
                        "oldFileName": d.a_path,
                    }, emitted_at=int(datetime.now().timestamp()) * 1000),
                )
            for diffCopied in currentDiff.iter_change_type("C"):
                d = cast(Diff, diffCopied)
                blob = safeRead(d.a_blob.data_stream)
                yield AirbyteMessage(
                    type=Type.RECORD,
                    record=AirbyteRecordMessage(stream=stream_name, data={
                        "hash": commitCursor.hexsha,
                        "authorName": commitCursor.author.name,
                        "authorEmail": commitCursor.author.email,
                        "date": commitCursor.committed_datetime.isoformat(),
                        "message": commitCursor.message,
                        "branch": config["branch"],
                        "repository": config["repoUrl"],
                        "size": d.a_blob.size,
                        "loc": len(blob.splitlines()),
                        "fileName": d.a_path,
                        "operation": "add",
                        "newContent": blob,
                        "oldContent": "",
                        "oldSize": 0,
                        "oldLoc": 0,
                        "oldFileName": "",
                    }, emitted_at=int(datetime.now().timestamp()) * 1000),
                )

            commitCursor = prevCommit
        if catalog.streams[0].sync_mode == SyncMode.incremental:
            yield AirbyteMessage(type=Type.STATE, state=AirbyteStateMessage(data={"lastHash": rep.commit(config["branch"]).hexsha }))